### ISSUE TITLE
[SDK] agent interview explicit edit action logging

### ISSUE THREAD

**Issue by avaer** [UpstreetAI/upstreet-core#466]
The agent interview currently deals only in chat, without necessarily telling you all of the edits it's making.

It might help the flow to output the edits as they happen so it's more transparent what effect your actions are having on the agent.

E.g.

[updated name to "blah"]
[enabled text to speech with voice "bleh"]

**Comment by DomoMKT** [comment]
you can find a free, no-account-needed solution for converting text to high-quality speech with low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com).
