### ISSUE TITLE
Custom voices limit per user

### ISSUE THREAD

**Issue by avaer** [UpstreetAI/upstreet-core#612]
Right now there are no limits on the number of `usdk voice`s that a user can upload, but it should be at least limited per account (the backend platforms will generally enforce this, so we have no choice).

![image](https://cdn.discordapp.com/attachments/1184011399576432691/1308733990441713695/image.png?ex=673f0502&is=673db382&hm=75fd83985cd9bc007b10c91140d4a7353134267bc25d287fb1d8f297b23cec22&)

**Comment by AbdurrehmanSubhani** [comment]
Merged
