### ISSUE TITLE
Unable to Access Variables from .env.txt 

### ISSUE THREAD

**Issue by Rabeet8** [UpstreetAI/upstreet-core#720]
### Product

USDK (Upstreet Agents SDK)

### What happened?

While creating a personal assistant i have added few google calender keys in the `.env.txt` file but i am only accessing the default AGENT_TOKEN and WALLET_MNEMONIC keys in my `agent.tsx`. The google keys are showing as `undefined`.

I have used `useEnv` hook to access the variables

### Version

0.0.94

### What is your environment?

v22.11.0

**Comment by avaer** [comment]
Reproduced
